version: "3"

services:
  bot:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
    environment:
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
      AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
      AIRTABLE_REQUESTS_TABLE_URL: ${AIRTABLE_REQUESTS_TABLE_URL}
      AIRTABLE_VOLUNTEERS_TABLE_URL: ${AIRTABLE_VOLUNTEERS_TABLE_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MAPQUEST_KEY: ${MAPQUEST_KEY}
      NODE_ENV: ${NODE_ENV:-development}
      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID}
      SLACK_XOXB: ${SLACK_XOXB}
    volumes:
      - "./src:/srv/src"
